# Generated by Django 5.0.6 on 2024-07-13 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
